telegram_message_on_success:
    stage: messages
    allow_failure: true
    # dependencies:
    #     - start_production_services_job
    # when: on_success
    script:
        - curl -v http://proxy.govoru.com/?message=%E2%9C%85%20Success.%20Auto%20deploy%20on%20${CI_PROJECT_NAME}%20is%20completed,%20Pipeline:%20${CI_PIPELINE_URL}%20by%20${GITLAB_USER_LOGIN}
    # only:
    #     - production


telegram_message_on_failure:
    stage: messages
    allow_failure: true
    # dependencies:
    #     - start_production_services_job
    when: on_failure
    script:
        - curl -v http://proxy.govoru.com/?message=%E2%9D%8C%20Error.%20Auto%20deploy%20on%20${CI_PROJECT_NAME}%20is%20failed,%20Pipeline:%20${CI_PIPELINE_URL}%20by%20${GITLAB_USER_LOGIN}
    # only:
    #     - production
